In [1]:
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth, association_rules

df = pd.read_csv(r'D:\Dhika Ramadhan Saputra\Data Analist\Full Project\Market Basket Analysis (MBA) & Bundling Strategy\data\clean\clean_dataset.csv')
df

,order_id,user_id,product_id,product_name,aisle,department,add_to_cart_order,reordered,order_dow,order_hour_of_day,days_since_prior_order
0,2,202279,33120,Organic Egg Whites,eggs,dairy eggs,1,True,5,9,8.0
1,2,202279,28985,Michigan Organic Kale,fresh vegetables,produce,2,True,5,9,8.0
2,2,202279,9327,Garlic Powder,spices seasonings,pantry,3,False,5,9,8.0
3,2,202279,45918,Coconut Butter,oils vinegars,pantry,4,True,5,9,8.0
4,2,202279,30035,Natural Sweetener,baking ingredients,pantry,5,False,5,9,8.0
...,...,...,...,...,...,...,...,...,...,...,...
1007667,106411,73364,21292,Rainbow Bell Peppers,packaged produce,produce,3,True,0,15,7.0
1007668,106411,73364,41024,Tikka Masala,frozen meals,frozen,4,True,0,15,7.0
1007669,106412,124192,49235,Organic Half & Half,cream,dairy eggs,1,True,2,9,13.0
1007670,106412,124192,33489,Organic Peppermint Tea,tea,beverages,2,False,2,9,13.0
1007671,106412,124192,2814,Natural Raw Cane Turbinado Sugar,baking ingredients,pantry,3,False,2,9,13.0

In [2]:
# ubah long menjadi list-of-list berdasarkan order id
basket = df.groupby('order_id')['product_name'].apply(list).tolist()

# Inisialisasi TransactionEncoder
te = TransactionEncoder()

# fit dan Transform ke format matriks (gunakan sparse=True agar angka 0 tidak memakan memori RAM)
te_ary = te.fit(basket).transform(basket, sparse=True)

# masukkan ke DataFrame
df_encoded = pd.DataFrame.sparse.from_spmatrix(te_ary, columns=te.columns_)

# Cek hasil
print(f"Jumlah Transaksi: {df_encoded.shape[0]}")
print(f"Jumlah Produk Unik: {df_encoded.shape[1]}")
df_encoded.head()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_7424\2190360934.py:11: FutureWarning: Allowing arbitrary scalar fill_value in SparseDtype is deprecated. In a future version, the fill_value must be a valid value for the SparseDtype.subtype.
  df_encoded = pd.DataFrame.sparse.from_spmatrix(te_ary, columns=te.columns_)

Jumlah Transaksi: 100000
Jumlah Produk Unik: 35150

,#2 Coffee Filters,#2 Cone White Coffee Filters,#4 Natural Brown Coffee Filters,& Go! Hazelnut Spread + Pretzel Sticks,+Energy Black Cherry Vegetable & Fruit Juice,0 Calorie Acai Raspberry Water Beverage,0 Calorie Fuji Apple Pear Water Beverage,0 Calorie Strawberry Dragonfruit Water Beverage,0% Fat Black Cherry Greek Yogurt y,0% Fat Blueberry Greek Yogurt,...,with Sweet Cinnamon Bunches Cereal,with Twist Ties Sandwich & Storage Bags,with Xylitol Cinnamon 18 Sticks Sugar Free Gum,with Xylitol Island Berry Lime 18 Sticks Sugar Free Gum,with Xylitol Minty Sweet Twist 18 Sticks Sugar Free Gum,with Xylitol Original Flavor 18 Sticks Sugar Free Gum,with Xylitol Unwrapped Spearmint 50 Sticks Sugar Free Gum,with Xylitol Watermelon Twist 18 Sticks Sugar Free Gum,with a Splash of Mango Coconut Water,with a Splash of Pineapple Coconut Water
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# import pickle

# # Tentukan alamat folder yang benar (pastikan folder 'interim' sudah dibuat ya)
# save_path = r'D:\Dhika Ramadhan Saputra\Data Analist\Full Project\Market Basket Analysis (MBA) & Bundling Strategy\data\clean\one-hot_encoding.pkl'

# # Simpan menggunakan format Pickle
# with open(save_path, 'wb') as f:
#     pickle.dump(df_encoded, f)

# print("File OHE Sparse berhasil disimpan dalam format Pickle!")

File OHE Sparse berhasil disimpan dalam format Pickle!